[workspace]
members = [
    "components/logue_bind",
    "components/osc_waves",
    "components/osc_dummy",
    "components/osc_table32",
    "xtask",
]
resolver = "2"

[profile.release]
panic = "abort"
opt-level = "s"
# https://doc.rust-lang.org/cargo/reference/profiles.html#lto
lto = "off"
