[workspace]
members = ["components/logue_sdk_v2rs", "components/osc_waves"]
resolver = "2"

[profile.release]
panic = "abort"
opt-level = "s"
# https://doc.rust-lang.org/cargo/reference/profiles.html#lto
lto = "off"
